encoding: utf-8
markdown: kramdown 
permalink: /:year/:month/:day/:title/
url: http://www.darkkate.com
author: darkkate
highlighter: pygments # pygments: true
safe: true
paginate: 16
timezone: Asia/Shanghai

kramdown:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
   #- smart         # typographic substitutions with SmartyPants
gems:
  - jekyll-mentions
  - jemoji
