markdown: rdiscount
permalink: /:year-:month-:day/:title.html
url: http://www.darkkate.com
author: darkkate
highlighter: pygments # pygments: true
safe: true
paginate: 16

rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants

